import type { PageModel } from '../../src/shared/protocol';

export const orderPage: PageModel = {
  pageId: 'markdown/instances/customer-order/4500123.md',
  title: 'Customer order 4500123 — Hoffmann Automotive',
  skill: {
    id: 'customer-order',
    description: 'A customer order.',
    summary: 'One order per customer.',
    autonomy: 'review',
    layer: 'overlay',
    readOnly: false,
    backend: 'sql_view',
  },
  fields: [
    {
      name: 'status',
      label: 'status',
      kind: 'enum',
      render: 'badge',
      required: true,
      value: 'open',
      display: 'open',
      values: ['open', 'closed'],
    },
    {
      name: 'customer',
      label: 'Customer',
      kind: 'link',
      render: 'link',
      required: true,
      value: '[[customer::hoffmann]]',
      display: 'hoffmann',
      links: [{ skill: 'customer', id: 'hoffmann', wikilink: '[[customer::hoffmann]]' }],
    },
    {
      name: 'value_eur',
      label: 'value_eur',
      kind: 'float',
      render: 'money',
      required: false,
      value: 184200,
      display: '184,200.00',
    },
    {
      name: 'eta',
      label: 'eta',
      kind: 'date',
      render: 'date',
      required: false,
      value: '2026-10-02',
      display: '2026-10-02',
    },
    {
      name: 'urgent',
      label: 'urgent',
      kind: 'bool',
      render: 'text',
      required: false,
      value: true,
      display: 'yes',
    },
    {
      name: 'notes',
      label: 'notes',
      kind: 'string',
      render: 'markdown',
      required: false,
      value: 'Call **before** noon',
      display: 'Call **before** noon',
    },
  ],
  summary: 'Delivery at risk: the supplier moved the ETA twice.',
  body: [
    '# Sales order 0004500123',
    '',
    'Body text with a [[supplier::stahl-ag]] link.',
    '',
    '## Items',
    '',
    '| Item | Material | Description | Qty | Unit | Net value |',
    '|---|---|---|---:|---|---:|',
    '| 10 | GH-4711 | Gearbox housing, cast, 14 kg | 240 | PC | 62,400.00 |',
    '| 20 | TH-0815 | Tool holder, hardened | 80 | PC | 31,100.00 |',
    '',
    '## History',
    '',
    '- Order created from customer PO **HA-2026-0917** and confirmed.',
    '- Confirmation for `GH-4711` moved by 14 days.',
  ].join('\n'),
  lastWrittenBy: 'agent:supplier-risk',
  editable: false,
  actions: [
    { skill: 'supplier-risk', label: 'Reassess risk for 4500123 with an agent' },
    { skill: 'customer-notice', label: 'Customer notice for 4500123 with an agent' },
  ],
};
