import type { PageModel } from '../../src/shared/protocol';

export const orderPage: PageModel = {
  pageId: 'markdown/instances/customer-order/4500123.md',
  title: 'Customer order 4500123 — Hoffmann Automotive',
  skill: {
    id: 'customer-order',
    description: 'A customer order.',
    summary: 'One order per customer.',
    autonomy: 'review',
    layer: 'overlay',
    readOnly: false,
    backend: 'sql_view',
  },
  fields: [
    {
      name: 'status',
      label: 'status',
      kind: 'enum',
      render: 'badge',
      required: true,
      value: 'open',
      display: 'open',
      values: ['open', 'closed'],
    },
    {
      name: 'customer',
      label: 'Customer',
      kind: 'link',
      render: 'link',
      required: true,
      value: '[[customer::hoffmann]]',
      display: 'hoffmann',
      link: { skill: 'customer', id: 'hoffmann', wikilink: '[[customer::hoffmann]]' },
    },
    {
      name: 'value_eur',
      label: 'value_eur',
      kind: 'float',
      render: 'money',
      required: false,
      value: 184200,
      display: '184,200.00',
    },
    {
      name: 'eta',
      label: 'eta',
      kind: 'date',
      render: 'date',
      required: false,
      value: '2026-10-02',
      display: '2026-10-02',
    },
    {
      name: 'urgent',
      label: 'urgent',
      kind: 'bool',
      render: 'text',
      required: false,
      value: true,
      display: 'yes',
    },
    {
      name: 'notes',
      label: 'notes',
      kind: 'string',
      render: 'markdown',
      required: false,
      value: 'Call **before** noon',
      display: 'Call **before** noon',
    },
  ],
  summary: 'Delivery at risk: the supplier moved the ETA twice.',
  body: '# Order\n\nBody text with a [[supplier::stahl-ag]] link.',
  lastWrittenBy: 'agent:supplier-risk',
  editable: false,
  actions: [
    { skill: 'supplier-risk', label: 'Reassess risk for 4500123 with an agent' },
    { skill: 'customer-notice', label: 'Customer notice for 4500123 with an agent' },
  ],
};
