// Widget test for the autogenerated links footer: BACKLINKS (incoming
// neighbours) + OUTGOING LINKS (outgoing neighbours) render as clickable
// chips; tapping one re-centres the workspace on that neighbour.

import 'package:escurel_explore/client/escurel_client.dart';
import 'package:escurel_explore/client/models.dart';
import 'package:escurel_explore/crm/links_footer.dart';
import 'package:escurel_explore/md/frontmatter.dart';
import 'package:escurel_explore/state/providers.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import 'package:flutter_test/flutter_test.dart';

const _spine = 'markdown/instances/engagement__hoffmann-spine.md';
const _acmePage = 'markdown/instances/customer__acme.md';

class _StubClient implements EscurelClient {
  @override
  Future<List<Neighbour>> neighbours(
    String pageId, {
    LinkDirection direction = LinkDirection.both,
    String? linkSkill,
    String? asOf,
    String? scenario,
  }) async {
    if (direction == LinkDirection.incoming) {
      return const [Neighbour(src: 'x', dst: 'acme', linkSkill: 'customer')];
    }
    return const [
      Neighbour(src: _spine, dst: 'weber', linkSkill: 'contact'),
      Neighbour(src: _spine, dst: 'opp-h001', linkSkill: 'opportunity'),
    ];
  }

  @override
  Future<ResolveResult> resolve(String wikilink, {String? scenario}) async {
    if (wikilink == '[[customer::acme]]') {
      return const ResolveResult(
        pageId: _acmePage,
        skill: 'customer',
        pageType: PageType.instance,
        exists: true,
      );
    }
    return const ResolveResult(pageId: '', skill: '', pageType: PageType.instance, exists: false);
  }

  @override
  dynamic noSuchMethod(Invocation i) => throw UnimplementedError('${i.memberName}');
}

void main() {
  testWidgets('renders backlinks + outgoing links; a chip re-centres focus', (tester) async {
    final container = ProviderContainer(
      overrides: [
        escurelClientProvider.overrideWithValue(_StubClient()),
        currentPageIdProvider.overrideWith((ref) => _spine),
      ],
    );
    addTearDown(container.dispose);

    await tester.pumpWidget(
      UncontrolledProviderScope(
        container: container,
        child: const MaterialApp(
          home: Scaffold(body: SingleChildScrollView(child: LinksFooter())),
        ),
      ),
    );
    await tester.pumpAndSettle();

    expect(find.bySemanticsLabel('links-footer'), findsOneWidget);
    expect(find.text('BACKLINKS · 1'), findsOneWidget);
    expect(find.text('OUTGOING LINKS · 2'), findsOneWidget);
    expect(find.bySemanticsLabel('backlink:acme'), findsOneWidget);
    expect(find.bySemanticsLabel('outlink:weber'), findsOneWidget);
    expect(find.bySemanticsLabel('outlink:opp-h001'), findsOneWidget);

    // Tapping a backlink re-centres on it.
    await tester.tap(find.bySemanticsLabel('backlink:acme'));
    await tester.pumpAndSettle();
    expect(container.read(currentPageIdProvider), _acmePage);
    expect(container.read(navBackStackProvider), contains(_spine));
  });
}
