// The visual harness: the built component with the realistic fixture. `?preview=rows|fields|document|issue`
// shows the same page backed by a source system, with what that source holds beneath the form.
import '../../../webview/page-as-ui/main';
import type { EscurelPageAsUi } from '../../../webview/page-as-ui/page-as-ui';
import type { PreviewModel } from '../../../src/shared/preview';
import { orderPage } from '../../component/fixtures';

const PREVIEWS: Record<string, PreviewModel> = {
  rows: {
    kind: 'rows',
    readOnly: true,
    source: 'vw_order_lines_all',
    columns: ['order_id', 'item', 'customer', 'material', 'qty', 'net_value', 'currency'],
    rows: [
      ['order-4500123', '10', 'Hoffmann Automotive GmbH', 'GH-4711', '240', '62400', 'EUR'],
      ['order-4500131', '10', 'Kessler Werkzeugbau GmbH', 'TH-0815', '80', '31100', 'EUR'],
      ['order-4500131', '20', 'Kessler Werkzeugbau GmbH', 'GH-4711', '200', '66200', 'EUR'],
    ],
    truncated: true,
  },
  fields: {
    kind: 'fields',
    readOnly: true,
    source: 'sap-orders-api',
    fields: [
      { name: 'status', value: 'open' },
      { name: 'confirmed_delivery', value: '2026-10-19' },
      { name: 'carrier', value: 'DHL Freight' },
    ],
  },
  document: {
    kind: 'document',
    readOnly: true,
    chunks: [
      {
        anchor: 'c1',
        text: 'Framework agreement between Hoffmann Automotive GmbH and Meier-Guss GmbH.',
      },
      { anchor: 'c2', text: 'Delivery terms: confirmed dates bind the supplier for 30 days.' },
    ],
    total: 14,
    truncated: true,
  },
  issue: {
    kind: 'issue',
    readOnly: true,
    source: 'vw_order_lines_all',
    code: 'binding_degraded',
    message:
      'source schema drifted from the stored fingerprint; reads fail closed until re-validated',
  },
};

const el = document.querySelector('escurel-page-as-ui') as EscurelPageAsUi;
const params = new URLSearchParams(location.search);
const preview = PREVIEWS[params.get('preview') ?? ''];
const base = preview
  ? {
      ...orderPage,
      skill: { ...orderPage.skill, backend: 'sql_view', readOnly: true },
      resource: 'https://sap.example/vbak',
      preview,
    }
  : orderPage;
// `?variant=row`: the same order as ONE ROW of an `instances: rows` skill (read-only source + its notes).
// `?variant=external` / `external-down`: a row from a REST source, with a change that was applied / a
// source that cannot be reached and a change that did not go through.
const variant = params.get('variant');
const rowSource = {
  fetchedAt: '2026-10-03T12:03:44.000000Z',
  sourceFields: ['status', 'customer'],
  linked: { enabled: true, exists: true, orphan: false },
};
el.model =
  variant === 'stale-facts'
    ? {
        // A skill that declares its provenance and has outlived it: the word Stale, then the facts.
        ...base,
        skill: {
          ...base.skill,
          stale: true as const,
          facts: [
            'stale',
            'verified 2026-01-01',
            'generated by agent:supplier-risk',
            'stale after 30 days',
            '2 sources',
          ],
        },
      }
    : variant === 'row'
      ? { ...base, source: rowSource }
      : variant === 'external'
        ? {
            ...base,
            source: { ...rowSource, external: 'REST', etag: 'w1:abc', writableColumns: ['status'] },
            writeBack: {
              outcome: 'applied',
              at: '2026-10-03T12:05:00.000000Z',
              draftId: 'd1',
              attempts: 1,
            },
          }
        : variant === 'external-down-blank'
          ? {
              // The real shape of a page whose source did not answer: NO source column is known and
              // every source field is blank. Each shows a dash, never a blank row or an empty pill.
              ...base,
              fields: base.fields.map((f) => ({ ...f, value: undefined, display: '' })),
              source: {
                fetchedAt: '2026-10-03T12:03:44.000000Z',
                sourceFields: [],
                linked: { enabled: true, exists: false, orphan: false },
                external: 'REST' as const,
                issue: {
                  code: 'source_unavailable',
                  message: 'the source could not be reached right now; its values show as —',
                },
              },
            }
          : variant === 'external-down'
            ? {
                ...base,
                source: {
                  ...rowSource,
                  external: 'MCP',
                  issue: {
                    code: 'source_unavailable',
                    message:
                      'the source could not be reached right now (transport error); showing what is known',
                  },
                },
                writeBack: {
                  outcome: 'failed',
                  at: '2026-10-03T12:05:00.000000Z',
                  draftId: 'd1',
                  attempts: 0,
                },
              }
            : base;
