import type { Skill } from '../client';

type Okf = Pick<Skill, 'verified' | 'generated' | 'status' | 'stale_after' | 'sources'>;

const DAY = 86_400_000;

/**
 * An ISO-8601 duration (`P90D`, `P2W`, `PT36H`, `P1DT12H`) in milliseconds, or `undefined` when it is
 * not one. Years and months have no fixed length, so they are read as 365 and 30 days: a freshness
 * window does not need calendar exactness. Fractions and negatives are refused rather than guessed.
 */
export function isoDurationMs(text: string): number | undefined {
  const m =
    /^P(?:(\d+)Y)?(?:(\d+)M)?(?:(\d+)W)?(?:(\d+)D)?(?:T(?:(\d+)H)?(?:(\d+)M)?(?:(\d+)S)?)?$/.exec(
      text.trim(),
    );
  if (!m || text.trim() === 'P' || text.trim().endsWith('T')) return undefined;
  const n = (i: number) => Number(m[i] ?? 0);
  return (
    n(1) * 365 * DAY +
    n(2) * 30 * DAY +
    n(3) * 7 * DAY +
    n(4) * DAY +
    n(5) * 3_600_000 +
    n(6) * 60_000 +
    n(7) * 1000
  );
}

const DATE = /^\d{4}-\d{2}-\d{2}$/;

const instant = (text: string | undefined): number | undefined => {
  if (!text) return undefined;
  const t = Date.parse(DATE.test(text.trim()) ? `${text.trim()}T00:00:00Z` : text);
  return Number.isNaN(t) ? undefined : t;
};

export interface SkillFacts {
  /** Short phrases for a tooltip or a header; `stale` comes first when the skill has gone stale. */
  facts: string[];
  stale: boolean;
}

/**
 * What a skill says about its own provenance and freshness (the OKF keys), as short phrases, and
 * whether it has gone stale: `verified` plus the `stale_after` duration is in the past, or an
 * absolute `stale_after` instant has passed. A bare duration cannot make a skill stale: nothing says
 * when its clock started. Never throws on junk; an unreadable value just says nothing.
 */
export function skillFacts(skill: Okf, now: number): SkillFacts {
  const facts: string[] = [];
  const verified = typeof skill.verified === 'string' ? skill.verified.trim() : '';
  const generated = typeof skill.generated === 'string' ? skill.generated.trim() : '';
  const status = typeof skill.status === 'string' ? skill.status.trim() : '';
  const staleAfter = typeof skill.stale_after === 'string' ? skill.stale_after.trim() : '';

  let stale = false;
  if (staleAfter) {
    const window = isoDurationMs(staleAfter);
    const from = instant(verified);
    if (window !== undefined && from !== undefined) stale = from + window < now;
    else if (window === undefined) {
      const at = instant(staleAfter);
      if (at !== undefined) stale = at < now;
    }
  }

  if (stale) facts.push('stale');
  if (verified) facts.push(`verified ${verified}`);
  if (generated)
    facts.push(DATE.test(generated) ? `generated ${generated}` : `generated by ${generated}`);
  if (status) facts.push(`status ${status}`);
  if (staleAfter) facts.push(`stale after ${staleAfter}`);
  const sources = Array.isArray(skill.sources) ? skill.sources.length : 0;
  if (sources) facts.push(`${sources} ${sources === 1 ? 'source' : 'sources'}`);
  return { facts, stale };
}
