/// Autogenerated link footer at the bottom of an instance/skill document:
/// the page's **backlinks** (incoming neighbours) and **outgoing links**
/// (outgoing neighbours), each a clickable skill-coloured chip that
/// re-centres the workspace on that entity. Pure composition over the
/// `neighbours` tool — backlinks vs outgoing are two directional calls.
library;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../client/models.dart';
import '../state/providers.dart';
import '../theme/app_theme.dart';
import '../widgets/entity_chip.dart';
import 'crm_providers.dart';

class LinksFooter extends ConsumerWidget {
  const LinksFooter({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final backlinks = ref.watch(currentBacklinksProvider).valueOrNull ?? const <Neighbour>[];
    final outgoing = ref.watch(currentOutgoingLinksProvider).valueOrNull ?? const <Neighbour>[];
    if (backlinks.isEmpty && outgoing.isEmpty) return const SizedBox.shrink();

    return Semantics(
      label: 'links-footer',
      container: true,
      explicitChildNodes: true,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Divider(height: 32, color: kOutlineVariant),
          if (backlinks.isNotEmpty)
            _Section(title: 'BACKLINKS', prefix: 'backlink', links: backlinks, incoming: true),
          if (backlinks.isNotEmpty && outgoing.isNotEmpty) const SizedBox(height: 20),
          if (outgoing.isNotEmpty)
            _Section(title: 'OUTGOING LINKS', prefix: 'outlink', links: outgoing, incoming: false),
        ],
      ),
    );
  }
}

class _Section extends ConsumerWidget {
  const _Section({
    required this.title,
    required this.prefix,
    required this.links,
    required this.incoming,
  });
  final String title;
  final String prefix;
  final List<Neighbour> links;

  /// Backlinks (incoming) show the *source* page (`n.src`, which links to
  /// us); outgoing links show the *target* (`n.dst`).
  final bool incoming;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final text = Theme.of(context).textTheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          '$title · ${links.length}',
          style: text.labelSmall?.copyWith(color: kOutline, letterSpacing: 1),
        ),
        const SizedBox(height: 10),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: [
            for (final n in links) _chip(ref, n),
          ],
        ),
      ],
    );
  }

  Widget _chip(WidgetRef ref, Neighbour n) {
    if (incoming) {
      // The "other end" is the source page that links to us; navigate to
      // it by its page id, label/colour it by its own skill.
      final (skill, slug) = _skillSlug(n.src);
      return EntityChip(
        skill: skill,
        label: slug,
        semanticsLabel: '$prefix:$slug',
        onTap: () => navigateToInstance(ref, n.src),
      );
    }
    return EntityChip(
      skill: n.linkSkill,
      label: n.dst,
      semanticsLabel: '$prefix:${n.dst}',
      onTap: () => focusWikilink(ref, n.linkSkill, n.dst),
    );
  }
}

/// Split a page id/ref (`markdown/instances/contact__reiter.md`,
/// `contact__reiter`, or a bare slug) into `(skill, slug)`.
(String, String) _skillSlug(String pageId) {
  final base = pageId.split('/').last.replaceAll('.md', '');
  final parts = base.split('__');
  return parts.length == 2 ? (parts[0], parts[1]) : ('', base);
}
