import { describe, expect, it } from 'vitest';
import { isoDurationMs, skillFacts } from '../../src/shared/freshness';

const NOW = Date.parse('2026-10-04T12:00:00Z');

describe('isoDurationMs', () => {
  it('reads the common ISO-8601 durations', () => {
    expect(isoDurationMs('P90D')).toBe(90 * 86_400_000);
    expect(isoDurationMs('P2W')).toBe(14 * 86_400_000);
    expect(isoDurationMs('PT36H')).toBe(36 * 3_600_000);
    expect(isoDurationMs('P1DT12H')).toBe(36 * 3_600_000);
  });

  it('refuses what is not a duration, instead of guessing', () => {
    for (const bad of ['', 'P', 'PT', '90 days', '2026-01-01', 'P-1D', 'P1.5D']) {
      expect(isoDurationMs(bad)).toBeUndefined();
    }
  });
});

describe('skillFacts', () => {
  it('shows nothing for a skill that declares nothing', () => {
    expect(skillFacts({}, NOW)).toEqual({ facts: [], stale: false });
  });

  it('says in short words what the skill declares', () => {
    const { facts } = skillFacts(
      {
        verified: '2026-09-30',
        generated: 'agent:supplier-risk',
        status: 'draft',
        stale_after: 'P90D',
        sources: ['https://sap.example/doc', { title: 'SAP', url: 'https://sap.example' }],
      },
      NOW,
    );
    expect(facts).toEqual([
      'verified 2026-09-30',
      'generated by agent:supplier-risk',
      'status draft',
      'stale after P90D',
      '2 sources',
    ]);
  });

  it('is stale when the duration since `verified` has run out', () => {
    expect(skillFacts({ verified: '2026-06-01', stale_after: 'P90D' }, NOW).stale).toBe(true);
    expect(skillFacts({ verified: '2026-09-30', stale_after: 'P90D' }, NOW).stale).toBe(false);
  });

  it('is stale when an absolute `stale_after` instant has passed', () => {
    expect(skillFacts({ stale_after: '2026-10-01T00:00:00Z' }, NOW).stale).toBe(true);
    expect(skillFacts({ stale_after: '2027-01-01' }, NOW).stale).toBe(false);
  });

  it('cannot call a skill stale from a duration alone: nothing says when the clock started', () => {
    expect(skillFacts({ stale_after: 'P90D' }, NOW).stale).toBe(false);
  });

  it('puts the word stale first, and never throws on junk', () => {
    expect(skillFacts({ verified: '2026-01-01', stale_after: 'P30D' }, NOW).facts[0]).toBe('stale');
    expect(() =>
      skillFacts({ verified: 'yesterday', stale_after: 'soon', sources: 'x' as never }, NOW),
    ).not.toThrow();
  });

  it('wording for a single source and a long generator', () => {
    expect(skillFacts({ sources: ['https://a'] }, NOW).facts).toEqual(['1 source']);
    expect(skillFacts({ generated: '2026-09-01' }, NOW).facts).toEqual(['generated 2026-09-01']);
  });
});
