/// Autogenerated link footer at the bottom of an instance/skill document:
/// the page's **backlinks** (incoming neighbours) and **outgoing links**
/// (outgoing neighbours), each a clickable skill-coloured chip that
/// re-centres the workspace on that entity. Pure composition over the
/// `neighbours` tool — backlinks vs outgoing are two directional calls.
library;

import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../client/models.dart';
import '../state/providers.dart';
import '../theme/app_theme.dart';
import '../widgets/entity_chip.dart';
import 'crm_providers.dart';

class LinksFooter extends ConsumerWidget {
  const LinksFooter({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final backlinks = ref.watch(currentBacklinksProvider).valueOrNull ?? const <Neighbour>[];
    final outgoing = ref.watch(currentOutgoingLinksProvider).valueOrNull ?? const <Neighbour>[];
    if (backlinks.isEmpty && outgoing.isEmpty) return const SizedBox.shrink();

    return Semantics(
      label: 'links-footer',
      container: true,
      explicitChildNodes: true,
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          const Divider(height: 32, color: kOutlineVariant),
          if (backlinks.isNotEmpty)
            _Section(title: 'BACKLINKS', prefix: 'backlink', links: backlinks),
          if (backlinks.isNotEmpty && outgoing.isNotEmpty) const SizedBox(height: 20),
          if (outgoing.isNotEmpty)
            _Section(title: 'OUTGOING LINKS', prefix: 'outlink', links: outgoing),
        ],
      ),
    );
  }
}

class _Section extends ConsumerWidget {
  const _Section({required this.title, required this.prefix, required this.links});
  final String title;
  final String prefix;
  final List<Neighbour> links;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final text = Theme.of(context).textTheme;
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Text(
          '$title · ${links.length}',
          style: text.labelSmall?.copyWith(color: kOutline, letterSpacing: 1),
        ),
        const SizedBox(height: 10),
        Wrap(
          spacing: 8,
          runSpacing: 8,
          children: [
            for (final n in links)
              EntityChip(
                skill: n.linkSkill,
                label: n.dst,
                semanticsLabel: '$prefix:${n.dst}',
                onTap: () => focusWikilink(ref, n.linkSkill, n.dst),
              ),
          ],
        ),
      ],
    );
  }
}
