//! The registry of every `ESCUREL_*` variable the workspace reads, and the ONE source of the operator
//! environment table (`docs/deploy/env.md`, generated by `escurel-server --print-config-keys`).
//!
//! `tests/suite/config_keys.rs` fails when a key read in the sources is missing here, when a key here is
//! not read anywhere, when the committed table is stale, and when an operator document names a variable
//! that does not exist. Add the key HERE when you add the `env.get(..)` / `std::env::var(..)` call.

/// One documented variable. `name` ending in `<N>` / `<NAME>` is a family (a numbered or named series).
#[derive(Debug, Clone, Copy)]
pub struct ConfigKey {
    pub name: &'static str,
    /// Free text naming who reads it (`Server`, `Runner`, `Server / Runner`, ...).
    pub component: &'static str,
    pub default: &'static str,
    pub doc: &'static str,
}

/// Every variable, grouped by who reads it.
pub const CONFIG_KEYS: &[ConfigKey] = &[
    ConfigKey {
        name: "ESCUREL_CONFIG",
        component: "Server",
        default: "—",
        doc: "path to a TOML base file; env vars override it",
    },
    ConfigKey {
        name: "VERSION",
        component: "Server",
        default: "0.0.0-dev",
        doc: "body of `GET /version` (alias of `ESCUREL_VERSION`)",
    },
    ConfigKey {
        name: "ESCUREL_VERSION",
        component: "Server",
        default: "0.0.0-dev",
        doc: "body of `GET /version`",
    },
    ConfigKey {
        name: "ENV",
        component: "Server",
        default: "dev",
        doc: "log field `env` (alias of `ESCUREL_ENV`)",
    },
    ConfigKey {
        name: "ESCUREL_ENV",
        component: "Server",
        default: "dev",
        doc: "log field `env`",
    },
    ConfigKey {
        name: "ESCUREL_SERVER_DATA_DIR",
        component: "Server",
        default: "/data",
        doc: "host-volume root for DuckDB + FsStore + tenants",
    },
    ConfigKey {
        name: "ESCUREL_SEED_DIR",
        component: "Server",
        default: "—",
        doc: "markdown corpus seeded into the tenant at boot (idempotent), e.g. `examples/crm-demo`",
    },
    ConfigKey {
        name: "ESCUREL_WEBHOOK_URL",
        component: "Server",
        default: "—",
        doc: "outbound capture webhook; fire-and-forget POST of each new `capture_event` (M7)",
    },
    ConfigKey {
        name: "ESCUREL_WEBHOOK_SECRET",
        component: "Server / Runner",
        default: "—",
        doc: "shared secret; when set the webhook body is HMAC-SHA256-signed via `X-Escurel-Webhook-Signature: sha256=<hex>` The runner requires the same HMAC signature on inbound `POST /trigger`.",
    },
    ConfigKey {
        name: "ESCUREL_SERVER_LISTEN_HTTP",
        component: "Server",
        default: "0.0.0.0:8080",
        doc: "HTTP listener (MCP/WS/REST)",
    },
    ConfigKey {
        name: "ESCUREL_TENANT",
        component: "Server",
        default: "default",
        doc: "single-tenant indexer's tenant id",
    },
    ConfigKey {
        name: "ESCUREL_REBUILD_INDEX_ON_BOOT",
        component: "Server",
        default: "if-missing",
        doc: "derived-index boot policy: `if-missing` (reuse an existing DuckDB; rebuild only when absent, and the default everywhere including the container) or `always` (drop + rebuild from the markdown LaneStore each start — re-embeds the whole corpus, so expect minutes)",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_BACKEND",
        component: "Server",
        default: "fs",
        doc: "`fs`, `s3`, `gcs` or `duckvfs`",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_DUCKVFS_ROOT",
        component: "Server",
        default: "—",
        doc: "root URL, e.g. `gdrive://escurel/lanes` (backend=duckvfs); its scheme picks the filesystem",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_DUCKVFS_EXTENSION",
        component: "Server",
        default: "—",
        doc: "path to a built `gdrive.duckdb_extension` (backend=duckvfs); needed for every scheme, not only `gdrive://`. Prefer `…_EXTENSION_REPO` — a path is a local build a container does not have",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_DUCKVFS_EXTENSION_REPO",
        component: "Server",
        default: "—",
        doc: "`community` (the DuckDB community repository) or a repository URL, used when `…_EXTENSION` is unset. Setting NEITHER skips the load rather than failing, so the store opens and the first WRITE fails on a missing `write_blob`",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_DUCKVFS_DRIVE_ID",
        component: "Server",
        default: "—",
        doc: "Shared Drive id `0A…`; REQUIRED for a `gdrive://` root, else the store would silently target the credential's My Drive",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_DUCKVFS_DRIVE_SCOPE",
        component: "Server",
        default: "…/auth/drive",
        doc: "OAuth scope; the default is read/write because the extension's own `drive.readonly` default cannot serve a lane store",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_GCS_BUCKET",
        component: "Server",
        default: "—",
        doc: "GCS bucket (backend=gcs)",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_GCS_PREFIX",
        component: "Server",
        default: "",
        doc: "GCS key prefix (backend=gcs)",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_GCS_CREDENTIALS_PATH",
        component: "Server",
        default: "—",
        doc: "service-account key file (backend=gcs); unset = ADC, i.e. the metadata server on GCP",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_GCS_ENDPOINT",
        component: "Server",
        default: "—",
        doc: "GCS endpoint override (backend=gcs); emulator/tests only",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_S3_BUCKET",
        component: "Server",
        default: "—",
        doc: "S3 bucket (backend=s3)",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_S3_ENDPOINT",
        component: "Server",
        default: "—",
        doc: "S3 endpoint URL (backend=s3)",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_S3_PREFIX",
        component: "Server",
        default: "",
        doc: "S3 key prefix (backend=s3)",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_S3_REGION",
        component: "Server",
        default: "us-east-1",
        doc: "S3 region label (backend=s3)",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_S3_ACCESS_KEY_ID",
        component: "Server",
        default: "—",
        doc: "S3 access key (backend=s3)",
    },
    ConfigKey {
        name: "ESCUREL_STORAGE_S3_SECRET_ACCESS_KEY",
        component: "Server",
        default: "—",
        doc: "S3 secret key (backend=s3)",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_OIDC_ISSUER",
        component: "Server",
        default: "—",
        doc: "OIDC issuer; unset → unauthenticated dev mode",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_OIDC_AUDIENCE",
        component: "Server",
        default: "escurel",
        doc: "OIDC audience",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_TENANT_CLAIM",
        component: "Server",
        default: "tenant",
        doc: "JWT claim carrying the tenant id",
    },
    ConfigKey {
        name: "ESCUREL_WRITE_ACL",
        component: "Server",
        default: "enforce",
        doc: "per-instance write ACL: `enforce` (reject; the default, also for an unrecognised value) | `log` (warn but allow) | `off` (no check, explicit opt-out). Symmetric to the read ACL: owner-or-admin writes; public/no-owner instances are admin-write-only.",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_ADMIN_ROLE_CLAIM",
        component: "Server",
        default: "roles",
        doc: "JWT claim listing roles",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_ADMIN_ROLE_VALUE",
        component: "Server",
        default: "escurel:admin",
        doc: "role value granting admin",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_JWKS_REFRESH_SECS",
        component: "Server",
        default: "300",
        doc: "JWKS cache TTL (seconds)",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_JWKS_URI",
        component: "Server",
        default: "derived from issuer",
        doc: "explicit JWKS URL (e.g. Triton's `<issuer>/.well-known/jwks.json`)",
    },
    ConfigKey {
        name: "ESCUREL_RUN_PROGRESS_KEEP",
        component: "Server",
        default: "50",
        doc: "how many `run-progress` snapshots a run keeps (pruned at capture)",
    },
    ConfigKey {
        name: "ESCUREL_SHUTDOWN_DRAIN_SECS",
        component: "Server",
        default: "25",
        doc: "how long a graceful stop waits for in-flight requests before aborting them (keep below the orchestrator's kill timeout)",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_SIGNING_KEY",
        component: "Server",
        default: "—",
        doc: "RSA private key (PKCS#8 or PKCS#1 PEM) the gateway signs `mint_agent_token` bearers with; unset → the tool refuses `unsupported`",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_SIGNING_KID",
        component: "Server",
        default: "derived",
        doc: "the `kid` those bearers carry (must be in a trusted JWKS)",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_SIGNING_ISSUER",
        component: "Server",
        default: "the OIDC issuer",
        doc: "the `iss` those bearers carry (must be a trusted issuer)",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_OIDC_ISSUER_2",
        component: "Server",
        default: "—",
        doc: "optional SECOND trusted issuer (e.g. Carl, for the dashboard's self-minted token); shares the audience + tenant claim",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_JWKS_URI_2",
        component: "Server",
        default: "derived from issuer #2",
        doc: "explicit JWKS URL for the second issuer (e.g. Carl's `<issuer>/jwks.json`)",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_OIDC_ISSUER_<N>",
        component: "Server",
        default: "—",
        doc: "further trusted issuers, read as a contiguous `_2.._N` sequence (e.g. `_3` = the escurel-explore BFF's browser auth bridge); a gap stops the scan",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_JWKS_URI_<N>",
        component: "Server",
        default: "derived from issuer #N",
        doc: "explicit JWKS URL for the Nth issuer",
    },
    ConfigKey {
        name: "ESCUREL_EMBEDDING_PROVIDER",
        component: "Server",
        default: "gemini",
        doc: "`zero`, `gemini`, or `embeddinggemma` (a candle BERT-family sentence-transformer; ONLY in a binary built with `--features embeddinggemma`: the default build and the image refuse to boot with it). `gemini` with no key falls back to zero",
    },
    ConfigKey {
        name: "ESCUREL_EMBEDDING_MODEL",
        component: "Server",
        default: "provider default",
        doc: "model id (candle default: `BAAI/bge-base-en-v1.5`, a BERT sentence-transformer — the candle backend has no Gemma3 path yet, see #299)",
    },
    ConfigKey {
        name: "ESCUREL_EMBEDDING_DEVICE",
        component: "Server",
        default: "cpu",
        doc: "candle device (informational; CPU only today)",
    },
    ConfigKey {
        name: "ESCUREL_EMBEDDING_DIM",
        component: "Server",
        default: "768",
        doc: "vector dimension",
    },
    ConfigKey {
        name: "ESCUREL_EMBEDDER_REQUIRED",
        component: "Server",
        default: "false",
        doc: "when `true`, a failed real-embedder load aborts boot instead of silently degrading to zero-vector (FTS-only) retrieval (#299)",
    },
    ConfigKey {
        name: "ESCUREL_GEMINI_API_KEY",
        component: "Server / Runner / Loader",
        default: "—",
        doc: "Gemini API key (provider=gemini; unset → zero fallback)",
    },
    ConfigKey {
        name: "ESCUREL_INDEX_BACKEND",
        component: "Server",
        default: "single-file",
        doc: "`single-file` or `ducklake` — selects the [`escurel_index::snapshot::IndexStore`] backend (DuckLake PR 6)",
    },
    ConfigKey {
        name: "ESCUREL_ROLE",
        component: "Server",
        default: "writer",
        doc: "`writer` or `reader` — `reader` requires `ESCUREL_INDEX_BACKEND=ducklake`; a reader boots with NO local single-file DuckDB, adopting the lake's newest published snapshot instead",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_CATALOG_DSN",
        component: "Server",
        default: "—",
        doc: "DuckLake catalog DSN — a Postgres key/value DSN (contains `=`) or a DuckDB-file catalog path; required when `ESCUREL_INDEX_BACKEND=ducklake`",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_DATA_PATH",
        component: "Server",
        default: "—",
        doc: "DuckLake `DATA_PATH` — `gs://…`, `s3://…`, `gdrive://…`, or a local directory; required when `ESCUREL_INDEX_BACKEND=ducklake`",
    },
    ConfigKey {
        name: "ESCUREL_CHAT_BACKEND",
        component: "Server",
        default: "postgres",
        doc: "`postgres` or `ducklake` — where chat history lives when `ESCUREL_INDEX_BACKEND=ducklake` and the catalog is Postgres",
    },
    ConfigKey {
        name: "ESCUREL_EVENTS_BACKEND",
        component: "Server",
        default: "postgres",
        doc: "as above, for the event bus",
    },
    ConfigKey {
        name: "ESCUREL_CRDT_PG_DSN",
        component: "Server",
        default: "the catalog DSN",
        doc: "Postgres holding `crdt_ops`/`crdt_snapshots`. Separate knob from the catalog because it holds customer document bytes, not lake metadata",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_GCS_KEY_ID",
        component: "Server",
        default: "—",
        doc: "GCS HMAC key pair; required when `ESCUREL_DUCKLAKE_DATA_PATH` starts with `gs://`",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_GCS_SECRET",
        component: "Server",
        default: "—",
        doc: "GCS HMAC key pair; required when `ESCUREL_DUCKLAKE_DATA_PATH` starts with `gs://`",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_S3_ENDPOINT",
        component: "Server",
        default: "—",
        doc: "S3 (or MinIO) credentials; required when `ESCUREL_DUCKLAKE_DATA_PATH` starts with `s3://`",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_S3_ACCESS_KEY_ID",
        component: "Server",
        default: "—",
        doc: "S3 (or MinIO) credentials; required when `ESCUREL_DUCKLAKE_DATA_PATH` starts with `s3://`",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_S3_SECRET_ACCESS_KEY",
        component: "Server",
        default: "—",
        doc: "S3 (or MinIO) credentials; required when `ESCUREL_DUCKLAKE_DATA_PATH` starts with `s3://`",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_S3_REGION",
        component: "Server",
        default: "us-east-1",
        doc: "S3 (or MinIO) credentials; required when `ESCUREL_DUCKLAKE_DATA_PATH` starts with `s3://`",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_S3_USE_SSL",
        component: "Server",
        default: "true",
        doc: "whether the S3/MinIO endpoint above is TLS",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_GDRIVE_DRIVE_ID",
        component: "Server",
        default: "—",
        doc: "Shared Drive id `0A…`; required when `ESCUREL_DUCKLAKE_DATA_PATH` starts with `gdrive://`. Expect this to be SLOW — DuckLake writes many small files and Drive charges a round trip per file, with no atomic overwrite",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_GDRIVE_SCOPE",
        component: "Server",
        default: "…/auth/drive",
        doc: "OAuth scope for the lake's Drive secret; credentials themselves come from ADC",
    },
    ConfigKey {
        name: "ESCUREL_DUCKLAKE_GDRIVE_EXTENSION",
        component: "Server",
        default: "—",
        doc: "path to a built `gdrive.duckdb_extension`; omit once it is installable by name from the community repository",
    },
    ConfigKey {
        name: "ESCUREL_ALLOW_UNSIGNED_EXTENSIONS",
        component: "Server",
        default: "false",
        doc: "permit `LOAD` of a locally-built, unsigned DuckDB extension. Required for the `gdrive` paths above. Off by default: an unsigned extension is arbitrary native code in-process",
    },
    ConfigKey {
        name: "ESCUREL_SNAPSHOT_REFRESH_SECS",
        component: "Server",
        default: "30",
        doc: "a reader's background lake-poll interval (seconds); see `escurel_server::snapshot_refresh::RefreshTask`",
    },
    ConfigKey {
        name: "ESCUREL_SNAPSHOT_PUBLISH_SECS",
        component: "Server",
        default: "unset",
        doc: "a writer's optional periodic publish interval (seconds); an explicit `0` disables it (manual-only, via the `publish_snapshot` admin tool). Unset: disabled, UNLESS chat/events are lake-backed (`ESCUREL_CHAT_BACKEND` / `ESCUREL_EVENTS_BACKEND` = `ducklake`), where the task doubles as append-table compaction and unset defaults to `300` — see `resolve_publish_secs` / `escurel_server::snapshot_publish::PublishTask`",
    },
    ConfigKey {
        name: "ESCUREL_SNAPSHOT_KEEP",
        component: "Server",
        default: "5",
        doc: "how many DuckLake snapshots to retain after a successful publish; the GC pass never touches the current snapshot",
    },
    ConfigKey {
        name: "ESCUREL_WRITER_LEASE",
        component: "Server",
        default: "on",
        doc: "ducklake-writer single-writer boot guard (#371): a catalog advisory lock refused when another live writer holds it; `off` disables — only if you guarantee a single writer yourself",
    },
    ConfigKey {
        name: "ESCUREL_EGRESS_ALLOW_LOOPBACK",
        component: "Server",
        default: "false",
        doc: "outbound connector calls (REST/MCP rows, write-back) may reach `127.0.0.1`. `1`/`true`/`0`/`false` only. **Dev and tests only** — never in production (SSRF guard); any other value fails the boot",
    },
    ConfigKey {
        name: "ESCUREL_EGRESS_MAX_RESPONSE_BYTES",
        component: "Server",
        default: "4194304",
        doc: "cap on one upstream response (streamed; over the cap → the call fails). Whole number ≥ 1",
    },
    ConfigKey {
        name: "ESCUREL_EGRESS_TIMEOUT_MS",
        component: "Server",
        default: "10000",
        doc: "total timeout of one upstream call; clamped to 30000. Whole number ≥ 1",
    },
    ConfigKey {
        name: "ESCUREL_EGRESS_MAX_CONCURRENCY",
        component: "Server",
        default: "8",
        doc: "simultaneous upstream calls per endpoint. Whole number ≥ 1",
    },
    ConfigKey {
        name: "ESCUREL_EGRESS_RATE_PER_SEC",
        component: "Server",
        default: "50",
        doc: "upstream calls per second per endpoint (token bucket). Whole number ≥ 1",
    },
    ConfigKey {
        name: "ESCUREL_EGRESS_WRITE_RETRY_BACKOFF_MS",
        component: "Server",
        default: "500",
        doc: "base backoff between write-back retries (a test knob; leave unset in production). Whole number ≥ 0",
    },
    ConfigKey {
        name: "ESCUREL_SECRET_<TENANT>__<NAME>",
        component: "Server",
        default: "—",
        doc: "a TENANT's credential, referenced as `secret_ref: gsm:<name>` or `env:ESCUREL_SECRET_<TENANT>__<NAME>` (injected from GCP Secret Manager). `<TENANT>` is the tenant id upper-cased, non-alphanumerics as `_` (`stuttgart-ai` → `STUTTGART_AI`). The namespace used to be global (`ESCUREL_SECRET_<NAME>`), so one tenant's admin could name another's secret",
    },
    ConfigKey {
        name: "ESCUREL_SECRET_ENV_ALLOW",
        component: "Server",
        default: "—",
        doc: "extra env var names a tenant may name as `env:NAME`: `tenant:NAME` for one tenant, a bare `NAME` for EVERY tenant (an explicit operator choice)",
    },
    ConfigKey {
        name: "ESCUREL_SECRET_FILE_DIRS",
        component: "Server",
        default: "/run/secrets",
        doc: "directories whose `<dir>/<tenant>/` sub-directory a tenant may name as `file:/path` (a tenant cannot read `<dir>/<other-tenant>/…`)",
    },
    ConfigKey {
        name: "ESCUREL_SQL_FILE_DIRS",
        component: "Server",
        default: "—",
        doc: "directories a `sqlite` credential's database file, and every `json_dir` / `parquet_dir` source's files, may live under (canonicalised; `..`, a symlink out and a glob reaching outside are refused). Unset refuses file databases AND directory sources. Postgres/MySQL credentials are checked like an endpoint: the connection string is parsed with libpq's grammar, only `host`, `hostaddr`, `port`, `dbname`, `user`, `password`, `sslmode`, `options`, `application_name`, `connect_timeout` are accepted (`service=`, `passfile=`, `sslrootcert=` … are refused), EVERY host/`hostaddr` must resolve to public addresses (loopback only with `ESCUREL_EGRESS_ALLOW_LOOPBACK`), and a host named by NAME is pinned to the address that was checked",
    },
    ConfigKey {
        name: "ESCUREL_CURSOR_KEY",
        component: "Server",
        default: "random per process",
        doc: "signing key of the list cursors (`next_cursor`). A cursor the server did not issue (forged, edited, issued before a restart) answers `invalid_cursor`. Set the SAME value on every replica (writer + readers) of one deployment so a client may page across them",
    },
    ConfigKey {
        name: "ESCUREL_ROWS_QUERY_TIMEOUT_SECS",
        component: "Server",
        default: "30",
        doc: "how long one `instances: rows` source query may run before it is interrupted (and, for Postgres, cancelled by the server itself). Whole number of seconds ≥ 1",
    },
    ConfigKey {
        name: "ESCUREL_SQL_CONNECT_TIMEOUT_SECS",
        component: "Server",
        default: "5",
        doc: "libpq `connect_timeout` for a network database source (Postgres), so a black-holed host cannot hold the tenant's index connection for the OS TCP timeout. Whole number of seconds ≥ 1",
    },
    ConfigKey {
        name: "ESCUREL_QUERY_TIMEOUT_MS",
        component: "Server",
        default: "see `escurel_index::DEFAULT_QUERY_TIMEOUT_MS`",
        doc: "per-query wall-clock bound on retrieval queries (#455); `0` disables the bound",
    },
    ConfigKey {
        name: "ESCUREL_EVENT_ACL",
        component: "Server",
        default: "off",
        doc: "per-event ACL on the event bus: `off` \\| `log` \\| `enforce`",
    },
    ConfigKey {
        name: "ESCUREL_TOOLCALL_DETAIL",
        component: "Server",
        default: "summary",
        doc: "what a run's recorded tool calls keep beyond sizes: `summary` (a bounded, redacted summary of each call's arguments and result, readable only by whoever may read the run) \\| `off` (sizes and timing only). An unrecognised value means `off`",
    },
    ConfigKey {
        name: "ESCUREL_AUTONOMY_LINT",
        component: "Server",
        default: "off",
        doc: "write-time lint of a skill page's `autonomy:` value: `off` \\| `log` \\| `enforce`",
    },
    ConfigKey {
        name: "ESCUREL_EMIT_EDIT_EVENTS",
        component: "Server",
        default: "false",
        doc: "`1`/`true`: emit an event per page edit (the eager per-edit improvement loop, #246)",
    },
    ConfigKey {
        name: "ESCUREL_INGEST_CONTEXTUALIZE",
        component: "Server",
        default: "structural",
        doc: "contextual-retrieval mode of ingested document chunks: `structural` or `off`; `llm` situates chunks with the endpoint below",
    },
    ConfigKey {
        name: "ESCUREL_CONTEXTUALIZE_LLM_ENDPOINT",
        component: "Server",
        default: "—",
        doc: "chat-completions endpoint used when `ESCUREL_INGEST_CONTEXTUALIZE=llm`",
    },
    ConfigKey {
        name: "ESCUREL_CONTEXTUALIZE_LLM_API_KEY",
        component: "Server",
        default: "—",
        doc: "bearer key for that endpoint",
    },
    ConfigKey {
        name: "ESCUREL_RETRIEVAL_RERANK",
        component: "Server",
        default: "`bge` when built with the `rerank` feature, else `off`",
        doc: "second-stage cross-encoder: `off` or `bge`",
    },
    ConfigKey {
        name: "ESCUREL_RETRIEVAL_RERANK_CANDIDATES",
        component: "Server",
        default: "100",
        doc: "how many first-stage candidates the reranker scores",
    },
    ConfigKey {
        name: "ESCUREL_RETRIEVAL_RERANK_MODEL",
        component: "Server",
        default: "BAAI/bge-reranker-v2-m3",
        doc: "reranker model id",
    },
    ConfigKey {
        name: "ESCUREL_RETRIEVAL_RERANK_DEVICE",
        component: "Server",
        default: "cpu",
        doc: "reranker device",
    },
    ConfigKey {
        name: "ESCUREL_RETRIEVAL_TWO_PASS",
        component: "Server",
        default: "false",
        doc: "Matryoshka two-pass vector search (`true`/`1`/`yes`/`on`)",
    },
    ConfigKey {
        name: "ESCUREL_RETRIEVAL_COARSE_DIM",
        component: "Server",
        default: "128",
        doc: "Matryoshka prefix length of the coarse pass (e.g. 128/256/512)",
    },
    ConfigKey {
        name: "ESCUREL_RETRIEVAL_COARSE_CANDIDATES",
        component: "Server",
        default: "500",
        doc: "candidates the coarse pass hands to the fine pass",
    },
    ConfigKey {
        name: "ESCUREL_OBSERVABILITY_METRICS_LISTEN",
        component: "Server",
        default: "0.0.0.0:9090",
        doc: "dedicated Prometheus `/metrics` listener; an explicitly empty value disables it",
    },
    ConfigKey {
        name: "ESCUREL_OBSERVABILITY_OTLP_ENDPOINT",
        component: "Server",
        default: "—",
        doc: "OTLP endpoint for traces (falls back to `ESCUREL_OTLP_ENDPOINT`); unset = no export",
    },
    ConfigKey {
        name: "ESCUREL_OTLP_ENDPOINT",
        component: "Server / Runner",
        default: "—",
        doc: "OTLP endpoint (server: fallback of the variable above; runner: its only knob)",
    },
    ConfigKey {
        name: "ESCUREL_PACK_SECRET",
        component: "Server",
        default: "—",
        doc: "HMAC secret that signs/verifies skill packs (also read by `escurel admin pack …`)",
    },
    ConfigKey {
        name: "ESCUREL_OPERATION_SLUG_SECRET",
        component: "Server",
        default: "—",
        doc: "secret the async-operation slugs are derived with",
    },
    ConfigKey {
        name: "ESCUREL_SEARCH_MIN_SIMILARITY",
        component: "Server",
        default: "none (no floor)",
        doc: "minimum cosine similarity a vector candidate must clear to enter the vector arm; BM25 matches are never affected",
    },
    ConfigKey {
        name: "ESCUREL_SERVE_DEMO_DIR",
        component: "Server",
        default: "—",
        doc: "serve this directory (a built `escurel-explore` web bundle) at `/`",
    },
    ConfigKey {
        name: "ESCUREL_AUTH_GROUPS_CLAIM",
        component: "Server",
        default: "`groups`",
        doc: "JWT claim listing the caller's groups",
    },
    ConfigKey {
        name: "ESCUREL_INDEX_HNSW",
        component: "Server",
        default: "false",
        doc: "build the `vss` HNSW indexes (`true`/`1`/`yes`/`on`); off by default (large, slow to rebuild)",
    },
    ConfigKey {
        name: "ESCUREL_INDEX_EXTENSIONS",
        component: "Server",
        default: "—",
        doc: "comma-separated absolute paths of pre-built `.duckdb_extension` files to `LOAD` (the image bakes them)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_LISTEN",
        component: "Runner",
        default: "0.0.0.0:8088",
        doc: "address of the runner's own HTTP server (`/healthz`, `/version`, `POST /trigger`)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_GATEWAY_URL",
        component: "Runner",
        default: "http://127.0.0.1:8080",
        doc: "base URL of the escurel gateway exposing `/mcp`",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_ENV",
        component: "Runner",
        default: "dev",
        doc: "deployment environment stamped on every log record",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_TENANT",
        component: "Runner",
        default: "—",
        doc: "tenant whose inbox the poller drains; the poller is off when this or the token is absent",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_TOKEN",
        component: "Runner",
        default: "—",
        doc: "tenant-scoped bearer the runner presents to `/mcp`; a static token wins over minting",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_QUEUE_CAP",
        component: "Runner",
        default: "1024",
        doc: "bound of the dispatch queue (backpressure instead of unbounded growth)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_SEEN_CAP",
        component: "Runner",
        default: "4096",
        doc: "bound of the dedup seen-set",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_POLL_INTERVAL",
        component: "Runner",
        default: "30s",
        doc: "interval between inbox polls (`30s`, `1500ms`, `2m`)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_TAIL_MAX_AGE",
        component: "Runner",
        default: "10m",
        doc: "how old a request on a tailed label may be and still be acted on after a restart",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_STATUS_INTERVAL",
        component: "Runner",
        default: "30s",
        doc: "how often the runner reports its health as an `escurel:runner-status` event when nothing changed",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_HARNESS_ALLOW",
        component: "Runner",
        default: "the configured harness",
        doc: "comma-separated harnesses a manual start may ask for by name; others fail closed",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_ID",
        component: "Runner",
        default: "<HOSTNAME>:<pid>",
        doc: "this runner's name in its status reports",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_CANCEL_GRACE",
        component: "Runner",
        default: "5s",
        doc: "time a cancelled run's subprocess gets between SIGTERM and SIGKILL",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_LINT_INTERVAL",
        component: "Runner",
        default: "disabled",
        doc: "how often the runner synthesizes a `lint` event (the scheduled semantic-health pass)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_LEDGER_PATH",
        component: "Runner",
        default: "./escurel-runner-ledger.duckdb",
        doc: "runner-local durable run ledger (its own DuckDB file; use a path under `/data` in a deployment)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_HARNESS",
        component: "Runner",
        default: "echo",
        doc: "harness adapter: `echo`, `claude`, `codex`, `agy`, `muse`, `gemini`, `delegate`",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_CLAUDE_BIN",
        component: "Runner",
        default: "claude",
        doc: "path to the `claude` binary",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_CLAUDE_MODEL",
        component: "Runner",
        default: "—",
        doc: "`--model` passed to `claude`",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_CODEX_BIN",
        component: "Runner",
        default: "codex",
        doc: "path to the `codex` binary",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_CODEX_MODEL",
        component: "Runner",
        default: "—",
        doc: "`-m` passed to `codex`",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AGY_BIN",
        component: "Runner",
        default: "agy",
        doc: "path to the `agy` (Antigravity) binary",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AGY_MODEL",
        component: "Runner",
        default: "—",
        doc: "`--model` passed to `agy`",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AGY_HOME",
        component: "Runner",
        default: "the process HOME",
        doc: "home directory holding `agy`'s credentials",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_MUSE_BIN",
        component: "Runner",
        default: "muse",
        doc: "path to the `muse` binary",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_MUSE_MODEL",
        component: "Runner",
        default: "—",
        doc: "`--model` passed to `muse exec`",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_MUSE_CONFIG_HOME",
        component: "Runner",
        default: "$XDG_CONFIG_HOME or $HOME/.config",
        doc: "config directory holding `muse`'s provider credentials",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AUTH_ISSUER",
        component: "Runner",
        default: "—",
        doc: "issuer of the bearers the runner MINTS for itself instead of holding a static token",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AUTH_AUDIENCE",
        component: "Runner",
        default: "escurel",
        doc: "audience of minted bearers",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AUTH_KID",
        component: "Runner",
        default: "derived from the key",
        doc: "`kid` of minted bearers",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AUTH_SIGNING_KEY",
        component: "Runner",
        default: "—",
        doc: "private key (PEM) the runner signs its minted bearers with",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AUTH_SUBJECT",
        component: "Runner",
        default: "escurel-runner",
        doc: "`sub` of minted bearers (a service principal)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AUTH_TTL_SECS",
        component: "Runner",
        default: "1800",
        doc: "lifetime of each minted gateway bearer, in seconds",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_MAX_TURNS",
        component: "Runner",
        default: "the harness default",
        doc: "model-turn bound for the harness",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_GEMINI_MODEL",
        component: "Runner",
        default: "—",
        doc: "model id of the Gemini adapter",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_GEMINI_BASE_URL",
        component: "Runner",
        default: "—",
        doc: "Generative Language API base for the Gemini adapter (tests point it at a local server)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AGENT_A2A_URL",
        component: "Runner",
        default: "—",
        doc: "the agent's A2A endpoint the `delegate` harness posts to; unset disables delegation",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AGENT_A2A_AUDIENCE",
        component: "Runner",
        default: "—",
        doc: "`aud` of the runner→agent delegation token (the agent's audience, never escurel's)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_MAX_ATTEMPTS",
        component: "Runner",
        default: "3",
        doc: "reconciler attempts per run before it is recorded `failed`",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_RUN_TIMEOUT",
        component: "Runner",
        default: "300s",
        doc: "wall-clock bound on one run attempt",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_RETRY_BACKOFF",
        component: "Runner",
        default: "500ms",
        doc: "base backoff before the first reconciler retry (grows per attempt)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_UNAVAILABLE_GRACE",
        component: "Runner",
        default: "1800s",
        doc: "how long a run keeps waiting on a gateway that is not answering at all",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_MAX_DEPTH",
        component: "Runner",
        default: "8",
        doc: "cascade depth cap (`depth_exceeded` past it)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_MAX_RUNS_PER_ROOT",
        component: "Runner",
        default: "64",
        doc: "per-root run budget (`budget_exceeded` past it)",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_TENANT_RUNS_PER_MIN",
        component: "Runner",
        default: "120",
        doc: "per-tenant runs/min quota; over-budget triggers are throttled, not dead-lettered",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_TENANT_MAX_CONCURRENT",
        component: "Runner",
        default: "8",
        doc: "per-tenant concurrent in-flight runs",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_MAX_HARNESS_PROCS",
        component: "Runner",
        default: "16",
        doc: "global cap on concurrent harness subprocesses",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_EMIT_EVENTS",
        component: "Runner",
        default: "true",
        doc: "write run lifecycle as `escurel:run` system events on the gateway",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_AGENT_NARROW",
        component: "Runner",
        default: "false",
        doc: "narrow each run's agent token to its target skill's write groups instead of admin",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_DRAIN_TIMEOUT",
        component: "Runner",
        default: "30s",
        doc: "SIGTERM drain: how long shutdown lets in-flight runs finish",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_OUTBOUND_URL",
        component: "Runner",
        default: "—",
        doc: "channel courier endpoint the runner POSTs a terminal operation's result to; unset disables outbound delivery",
    },
    ConfigKey {
        name: "ESCUREL_RUNNER_OUTBOUND_BEARER",
        component: "Runner",
        default: "—",
        doc: "shared server-to-server bearer on the outbound delivery POST",
    },
    ConfigKey {
        name: "ESCUREL_SERVER",
        component: "Cli",
        default: "http://127.0.0.1:8080",
        doc: "HTTP endpoint the `escurel` CLI talks to (`--server`)",
    },
    ConfigKey {
        name: "ESCUREL_TOKEN",
        component: "Cli",
        default: "—",
        doc: "bearer token the `escurel` CLI presents (`--token`); unset against an unauthenticated server",
    },
    ConfigKey {
        name: "ESCUREL_MCP_BEARER",
        component: "Harness",
        default: "—",
        doc: "set by the runner in a harness subprocess: the scoped bearer for that run (never set it yourself)",
    },
    ConfigKey {
        name: "ESCUREL_ECHO_FAIL_SKILL",
        component: "TestOnly",
        default: "—",
        doc: "echo harness: fail runs targeting this skill (tests)",
    },
    ConfigKey {
        name: "ESCUREL_ECHO_RESULT_REF",
        component: "TestOnly",
        default: "—",
        doc: "echo harness: attach this result reference (tests)",
    },
    ConfigKey {
        name: "ESCUREL_ECHO_SLEEP_MS",
        component: "TestOnly",
        default: "0",
        doc: "echo harness: idle this long before finishing, so a test can cancel a run",
    },
    ConfigKey {
        name: "ESCUREL_ECHO_USAGE",
        component: "TestOnly",
        default: "—",
        doc: "echo harness: report this usage (tests)",
    },
    ConfigKey {
        name: "ESCUREL_TEST_GDRIVE_EXTENSION",
        component: "TestOnly",
        default: "—",
        doc: "path of a built gdrive extension for the duckvfs tests",
    },
    ConfigKey {
        name: "ESCUREL_TEST_MIGRATE_KIND_PAGE_DELAY_MS",
        component: "TestOnly",
        default: "—",
        doc: "sleep this long before each page of `migrate_kind`, to give a CI-sized tenant a long migration window",
    },
    ConfigKey {
        name: "ESCUREL_SIGKILL_FULL",
        component: "TestOnly",
        default: "—",
        doc: "`1`: run all ten kill points of the migrate-kind SIGKILL test (default: four)",
    },
    ConfigKey {
        name: "ESCUREL_SECRET_ACME__SURELY_UNSET_X",
        component: "TestOnly",
        default: "—",
        doc: "a name the secret-policy tests assert is NOT set",
    },
    ConfigKey {
        name: "ESCUREL_BIN_DIR",
        component: "Tooling",
        default: "—",
        doc: "directory holding the built binaries (`escurel`, `escurel-server`) for `scripts/migrate-kind-job.sh` and the extension e2e",
    },
    ConfigKey {
        name: "ESCUREL_JOB_DEADLINE_SECS",
        component: "Tooling",
        default: "3600",
        doc: "`migrate-kind-job`: boot + apply deadline",
    },
    ConfigKey {
        name: "ESCUREL_JOB_PORT",
        component: "Tooling",
        default: "8080",
        doc: "`migrate-kind-job`: loopback port of the throwaway server",
    },
    ConfigKey {
        name: "ESCUREL_HTTP_PORT",
        component: "Tooling",
        default: "8080",
        doc: "compose: host port mapped to the gateway's 8080",
    },
    ConfigKey {
        name: "ESCUREL_METRICS_PORT",
        component: "Tooling",
        default: "9090",
        doc: "compose: host port mapped to the metrics listener",
    },
    ConfigKey {
        name: "ESCUREL_SMOKE_PORT",
        component: "Tooling",
        default: "18080",
        doc: "`deploy/compose/smoke.sh`: base port of the smoke run",
    },
    ConfigKey {
        name: "ESCUREL_ENDPOINT",
        component: "Tooling",
        default: "—",
        doc: "`examples/echo-app`: gateway endpoint (the app's own variable, not read by the server)",
    },
];

/// The group order of the rendered table.
const GROUPS: &[(&str, &str)] = &[
    ("Server", "escurel-server"),
    ("Server / Runner", "read by both the server and the runner"),
    ("Server / Runner / Loader", "read by several binaries"),
    ("Runner", "escurel-runner (the agent runner)"),
    ("Cli", "the `escurel` CLI"),
    ("Harness", "set by the runner for a harness subprocess"),
    (
        "Tooling",
        "scripts, compose and examples (not read by the gateway)",
    ),
    ("TestOnly", "test knobs: never set in a deployment"),
];

/// The operator environment table as markdown: what `docs/deploy/env.md` holds, byte for byte.
#[must_use]
pub fn render_markdown() -> String {
    let mut out = String::from(
        "# Environment variables\n\n\
         <!-- GENERATED by `escurel-server --print-config-keys` from `crates/escurel-server/src/config_keys.rs`.\n     \
         Do not edit by hand: change the registry, then `escurel-server --print-config-keys > docs/deploy/env.md`.\n     \
         `crates/escurel-server/tests/suite/config_keys.rs` fails when this file is stale. -->\n\n\
         Every variable the binaries read. Env overrides the TOML base file at `$ESCUREL_CONFIG`.\n",
    );
    for (group, blurb) in GROUPS {
        let keys: Vec<&ConfigKey> = CONFIG_KEYS
            .iter()
            .filter(|k| k.component == *group)
            .collect();
        if keys.is_empty() {
            continue;
        }
        out.push_str(&format!(
            "\n## {group}\n\n{blurb}.\n\n| var | default | meaning |\n|---|---|---|\n"
        ));
        for k in keys {
            out.push_str(&format!(
                "| `{}` | {} | {} |\n",
                k.name,
                cell(k.default),
                cell(k.doc)
            ));
        }
    }
    out
}

fn cell(s: &str) -> String {
    s.replace('|', "\\|").replace('\n', " ")
}
