import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../client/models.dart';
import '../crm/links_footer.dart';
import '../md/wikilink.dart';
import '../state/providers.dart';
import '../theme/app_theme.dart';
import '../widgets/kind_chip.dart';
import '../widgets/wikilink_pill.dart';
import 'page_form.dart';

/// Center pane — the entity editor. Renders the focused page's
/// frontmatter as a key/value table and the body as paragraph text
/// with inline `[[wikilink]]` pills.
class EntityEditor extends ConsumerWidget {
  const EntityEditor({super.key, this.showLinks = false});

  /// Append the autogenerated backlinks/outgoing-links footer at the
  /// bottom of the document. On in the CRM instance pane (which has no
  /// backlinks rail); off in the editor demo (its right-rail already
  /// lists backlinks).
  final bool showLinks;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final async = ref.watch(currentPageProvider);
    final scheme = Theme.of(context).colorScheme;

    // Leave edit mode whenever the focused page changes — a stale draft
    // must never bleed across pages.
    ref.listen(currentPageIdProvider, (previous, next) {
      if (ref.read(editModeProvider)) {
        ref.read(editModeProvider.notifier).state = false;
        ref.read(pageDraftProvider.notifier).state = null;
        ref.read(pageValidationProvider.notifier).state = const [];
        ref.read(pageSaveProvider.notifier).state = SaveState.idle;
      }
    });

    return Container(
      key: const ValueKey('pane.editor'),
      color: scheme.surface,
      child: async.when(
        loading: () => const Center(child: CircularProgressIndicator(strokeWidth: 2)),
        error: (e, _) => Center(
          child: Text('$e', style: const TextStyle(color: kError)),
        ),
        data: (page) => page == null ? const _EmptyState() : _PageView(page: page, showLinks: showLinks),
      ),
    );
  }
}

class _EmptyState extends StatelessWidget {
  const _EmptyState();

  @override
  Widget build(BuildContext context) {
    final text = Theme.of(context).textTheme;
    return Center(
      child: Padding(
        padding: const EdgeInsets.all(32),
        child: Column(
          mainAxisSize: MainAxisSize.min,
          children: [
            Text('No page open', style: text.titleMedium?.copyWith(color: kOnSurfaceVariant)),
            const SizedBox(height: 4),
            Text(
              'Pick a skill or instance from the catalogue.',
              style: text.bodySmall?.copyWith(color: kOnSurfaceVariant),
            ),
          ],
        ),
      ),
    );
  }
}

class _PageView extends ConsumerWidget {
  const _PageView({required this.page, this.showLinks = false});

  final ExpandResult page;
  final bool showLinks;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final text = Theme.of(context).textTheme;
    final title = (page.frontmatter['name'] as String?) ??
        (page.frontmatter['title'] as String?) ??
        page.pageId;

    final editable = ref.watch(currentPageEditableProvider);
    final editing = ref.watch(editModeProvider);
    // The catalogue is loaded by the time the page is — resolve the
    // skill summary the form needs to drive its field set.
    final skills = ref.watch(skillsCatalogueProvider).asData?.value ?? const <SkillSummary>[];
    final matches = skills.where((s) => s.id == page.skill);
    final skill = matches.isEmpty ? null : matches.first;

    return SingleChildScrollView(
      key: const ValueKey('entity_editor.scroll'),
      padding: const EdgeInsets.all(24),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Row(
            children: [
              KindChip(pageType: page.pageType),
              const SizedBox(width: 8),
              Expanded(
                child: Text(page.pageId, style: text.bodySmall?.copyWith(color: kOnSurfaceVariant)),
              ),
              if (editable && !editing)
                Semantics(
                  label: PageFormKeys.editPage,
                  identifier: PageFormKeys.editPage,
                  button: true,
                  onTap: () => _enterEdit(ref),
                  excludeSemantics: true,
                  child: OutlinedButton.icon(
                    onPressed: () => _enterEdit(ref),
                    icon: const Icon(Icons.edit, size: 16),
                    label: const Text('Bearbeiten'),
                  ),
                ),
            ],
          ),
          const SizedBox(height: 8),
          Text(title, style: text.displayMedium, key: const ValueKey('entity_editor.title')),
          const SizedBox(height: 16),
          if (editing && skill != null)
            PageEditForm(
              key: ValueKey('edit:${page.pageId}'),
              skill: skill,
              pageId: page.pageId,
              baseVersion: page.version,
              isNew: false,
            )
          else ...[
            _FrontmatterTable(fields: page.frontmatter),
            const SizedBox(height: 24),
            _BodyBlock(body: page.body),
            // Autogenerated backlinks + outgoing links for this page (CRM).
            if (showLinks) const LinksFooter(),
          ],
        ],
      ),
    );
  }

  void _enterEdit(WidgetRef ref) {
    ref.read(pageDraftProvider.notifier).state = PageDraft(
      frontmatter: {...page.frontmatter},
      body: page.body,
    );
    ref.read(pageValidationProvider.notifier).state = const [];
    ref.read(pageSaveProvider.notifier).state = SaveState.idle;
    ref.read(editModeProvider.notifier).state = true;
  }
}

class _FrontmatterTable extends StatelessWidget {
  const _FrontmatterTable({required this.fields});

  final Map<String, dynamic> fields;

  @override
  Widget build(BuildContext context) {
    final entries = fields.entries.toList();
    final text = Theme.of(context).textTheme;
    return Container(
      key: const ValueKey('entity_editor.frontmatter'),
      decoration: BoxDecoration(
        color: kSurfaceContainerLow,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: kOutlineVariant),
      ),
      child: Column(
        children: [
          for (var i = 0; i < entries.length; i++) ...[
            if (i > 0) const Divider(height: 1, color: kOutlineVariant),
            Padding(
              padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 8),
              child: Row(
                crossAxisAlignment: CrossAxisAlignment.start,
                children: [
                  SizedBox(
                    width: 140,
                    child: Text(
                      entries[i].key,
                      style: text.labelLarge?.copyWith(color: kOnSurfaceVariant),
                    ),
                  ),
                  const SizedBox(width: 8),
                  Expanded(child: _ValueRender(value: entries[i].value)),
                ],
              ),
            ),
          ],
        ],
      ),
    );
  }
}

class _ValueRender extends ConsumerWidget {
  const _ValueRender({required this.value});

  final dynamic value;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    if (value == null) {
      return Text('—', style: Theme.of(context).textTheme.bodySmall?.copyWith(color: kOnSurfaceVariant));
    }
    final skillIds = ref.watch(skillsCatalogueProvider).maybeWhen(
          data: (skills) => skills.map((s) => s.id).toSet(),
          orElse: () => const <String>{},
        );
    // Flatten a scalar or list into atomic widgets: `[[wikilink]]`s and
    // bare skill-id values become pills (mirroring the body renderer),
    // everything else plain text. List values (e.g.
    // `required_frontmatter: [event]`) render item-by-item.
    final items = (value is List) ? (value as List).map((e) => e.toString()) : [value.toString()];
    final widgets = <Widget>[];
    for (final raw in items) {
      final refs = parseWikilinks(raw);
      if (refs.isNotEmpty) {
        widgets.addAll(refs.map((r) => WikilinkPill(ref: r)));
      } else if (skillIds.contains(raw.trim())) {
        widgets.add(WikilinkPill(ref: WikilinkRef(id: raw.trim())));
      } else {
        widgets.add(Text(raw, style: Theme.of(context).textTheme.bodyMedium));
      }
    }
    if (widgets.isEmpty) {
      return Text('—', style: Theme.of(context).textTheme.bodySmall?.copyWith(color: kOnSurfaceVariant));
    }
    // A lone plain-text scalar needs no Wrap (lets long descriptions wrap
    // naturally); anything with pills goes in a Wrap so a pill sizes to its
    // content instead of stretching across the row's Expanded slot.
    if (widgets.length == 1 && widgets.first is Text) return widgets.first;
    return Wrap(spacing: 6, runSpacing: 4, children: widgets);
  }
}

class _BodyBlock extends StatelessWidget {
  const _BodyBlock({required this.body});

  final String body;

  @override
  Widget build(BuildContext context) {
    final lines = body.trimLeft().split('\n');
    final text = Theme.of(context).textTheme;
    return Column(
      key: const ValueKey('entity_editor.body'),
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        for (final line in lines) _renderLine(context, line, text),
      ],
    );
  }

  Widget _renderLine(BuildContext context, String line, TextTheme text) {
    if (line.startsWith('### ')) {
      return Padding(
        padding: const EdgeInsets.only(top: 10, bottom: 4),
        child: Text(line.substring(4), style: text.titleMedium),
      );
    }
    if (line.startsWith('## ')) {
      return Padding(
        padding: const EdgeInsets.only(top: 12, bottom: 4),
        child: Text(line.substring(3), style: text.titleLarge),
      );
    }
    if (line.startsWith('# ')) {
      return Padding(
        padding: const EdgeInsets.only(top: 12, bottom: 6),
        child: Text(line.substring(2), style: text.headlineMedium),
      );
    }
    // Bullet list item (`- ` / `* `): a hanging-indent row whose source
    // marker is replaced by a bullet glyph, the content rendered inline.
    final bullet = RegExp(r'^[-*]\s+(.*)$').firstMatch(line);
    if (bullet != null) {
      return Padding(
        padding: const EdgeInsets.only(left: 8, bottom: 4),
        child: Row(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            Padding(
              padding: const EdgeInsets.only(right: 8, top: 1),
              child: Text('•', style: text.bodyMedium?.copyWith(color: kOnSurfaceVariant)),
            ),
            Expanded(child: _InlineMarkdown(text: bullet.group(1)!)),
          ],
        ),
      );
    }
    if (line.isEmpty) return const SizedBox(height: 8);
    return Padding(
      padding: const EdgeInsets.only(bottom: 4),
      child: _InlineMarkdown(text: line),
    );
  }
}

/// A paragraph (or list item) with inline markdown rendered as styled
/// spans: `**bold**`, `` `code` ``, `[label](target)` links, and the
/// `[[wikilink]]` pills the explorer already understood. Deliberately
/// CommonMark-*subset* (no italics/tables/blockquotes) — it covers what
/// the KB corpus actually uses, with no extra dependency.
class _InlineMarkdown extends ConsumerWidget {
  const _InlineMarkdown({required this.text});

  final String text;

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final base = Theme.of(context).textTheme.bodyMedium?.copyWith(color: kOnSurface);
    // The set of known skill ids — a `` `code` `` span whose content is a
    // skill id renders as a link to that skill (empty while the catalogue
    // loads, so code stays inert until it resolves).
    final skillIds = ref.watch(skillsCatalogueProvider).maybeWhen(
          data: (skills) => skills.map((s) => s.id).toSet(),
          orElse: () => const <String>{},
        );
    return Text.rich(
      TextSpan(style: base, children: inlineMarkdownSpans(context, text, skillIds)),
    );
  }
}

/// Earliest-match alternation over the four inline constructs. Order in
/// the union doesn't matter — `allMatches` walks left→right and a link's
/// own `[` is reached only after any preceding code/bold is consumed, so
/// an inline code span *inside* a link label (the corpus's
/// `` [`community`](community.md) ``) stays part of the link match and is
/// rendered when the label recurses through this same builder.
final _inlinePattern = RegExp(
  r'(?<code>`[^`\n]+`)'
  r'|(?<bold>\*\*[^\n]+?\*\*)'
  r'|(?<wiki>\[\[[^\[\]\r\n]+?\]\])'
  r'|(?<link>\[[^\]\n]+\]\([^)\n]+\))',
);

/// Tokenise [src] into styled inline spans. Exposed (package-private) so
/// both paragraphs and link labels share one code path. [skillIds] is the
/// set of known skill ids; a `` `code` `` span matching one becomes a link
/// to that skill.
List<InlineSpan> inlineMarkdownSpans(
  BuildContext context,
  String src,
  Set<String> skillIds,
) {
  final base = Theme.of(context).textTheme.bodyMedium;
  final spans = <InlineSpan>[];
  var cursor = 0;
  for (final m in _inlinePattern.allMatches(src)) {
    if (m.start > cursor) {
      spans.add(TextSpan(text: src.substring(cursor, m.start)));
    }
    final code = m.namedGroup('code');
    final bold = m.namedGroup('bold');
    final wiki = m.namedGroup('wiki');
    if (code != null) {
      final content = code.substring(1, code.length - 1);
      final codeStyle = base?.copyWith(
        fontFamily: 'monospace',
        fontFamilyFallback: const ['monospace'],
        backgroundColor: kSurfaceContainerHigh,
        color: kPrimary,
      );
      // A code span that names a skill renders as a wikilink pill — the
      // same affordance the frontmatter uses — so in-document skill links
      // look identical to the header's. Otherwise it's a plain code chip.
      if (skillIds.contains(content)) {
        spans.add(WidgetSpan(
          alignment: PlaceholderAlignment.middle,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 2),
            child: WikilinkPill(ref: WikilinkRef(id: content)),
          ),
        ));
      } else {
        spans.add(TextSpan(text: content, style: codeStyle));
      }
    } else if (bold != null) {
      final inner = bold.substring(2, bold.length - 2);
      for (final s in inlineMarkdownSpans(context, inner, skillIds)) {
        spans.add(_withWeight(s, base));
      }
    } else if (wiki != null) {
      final refs = parseWikilinks(wiki);
      if (refs.isEmpty) {
        spans.add(TextSpan(text: wiki));
      } else {
        spans.add(WidgetSpan(
          alignment: PlaceholderAlignment.middle,
          child: Padding(
            padding: const EdgeInsets.symmetric(horizontal: 2),
            child: WikilinkPill(ref: refs.first),
          ),
        ));
      }
    } else {
      final link = m.namedGroup('link')!;
      final parts = RegExp(r'^\[(.+)\]\((.+)\)$').firstMatch(link)!;
      spans.add(WidgetSpan(
        alignment: PlaceholderAlignment.middle,
        child: _MdLink(label: parts.group(1)!, target: parts.group(2)!),
      ));
    }
    cursor = m.end;
  }
  if (cursor < src.length) {
    spans.add(TextSpan(text: src.substring(cursor)));
  }
  return spans;
}

/// Force bold weight onto a text run; widget spans (pills/links) pass
/// through unchanged.
InlineSpan _withWeight(InlineSpan s, TextStyle? base) {
  if (s is TextSpan) {
    return TextSpan(
      text: s.text,
      children: s.children,
      style: (s.style ?? base)?.copyWith(fontWeight: FontWeight.bold),
    );
  }
  return s;
}

/// A `[label](target)` link. Styled like a link (primary + underline);
/// internal targets (a relative `*.md` page or a bare id) navigate via
/// the same `resolve` seam the wikilink pills use, so no `url_launcher`
/// dependency is pulled in. External `scheme://` targets render styled
/// but inert, with the URL in a tooltip.
class _MdLink extends ConsumerWidget {
  const _MdLink({required this.label, required this.target});

  final String label;
  final String target;

  bool get _internal => !target.contains('://') && !target.startsWith('mailto:');

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    final skillIds = ref.watch(skillsCatalogueProvider).maybeWhen(
          data: (skills) => skills.map((s) => s.id).toSet(),
          orElse: () => const <String>{},
        );
    final linkStyle = Theme.of(context).textTheme.bodyMedium?.copyWith(
          color: kPrimary,
          decoration: TextDecoration.underline,
          decorationColor: kPrimary,
        );
    final child = Text.rich(
      TextSpan(style: linkStyle, children: inlineMarkdownSpans(context, label, skillIds)),
    );
    if (!_internal) return Tooltip(message: target, child: child);
    // Strip a trailing `.md` and any path → the bare page id `focusSkill`
    // resolves as `[[id]]` → `markdown/skills/<id>.md`.
    final id = (target.endsWith('.md') ? target.substring(0, target.length - 3) : target)
        .split('/')
        .last;
    return InkWell(
      borderRadius: BorderRadius.circular(4),
      onTap: () => focusSkill(ref, id),
      child: child,
    );
  }
}